spring.application.name=algafood-service
spring.datasource.url=jdbc:mysql://localhost:3306/algafood?createDatabaseIfNotExist=true&connectionTimeZone=Africa/Maputo
spring.datasource.username=root
spring.datasource.password=algafoodroot

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
